---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: 'MyLaunchTemplate'
      LaunchTemplateData:
        ImageId: 'ami-0557a15b87f6559cf'  # Ubuntu 20.04 LTS
        InstanceType: 't2.micro'
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            echo "<?php echo 'Hello, World!'; ?>" > /var/www/html/index.php
            service apache2 start
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'My Security Group'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: '0.0.0.0/0'
  MyDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: 'mysql'
      DBInstanceClass: 'db.t2.micro'
      AllocatedStorage: '20'
      DBInstanceIdentifier: 'mydbinstance'
      MasterUsername: 'admin'
      MasterUserPassword: 'mypassword'
      VPCSecurityGroups:
        - !Ref MySecurityGroup
   MyEC2Instance1:
    Type: 'AWS::EC2::Instance'
    Properties:
      LaunchTemplate:
        LaunchTemplateName: !Ref MyLaunchTemplate
      SecurityGroupIds:
        - !Ref MySecurityGroup
  MyEC2Instance2:
    Type: 'AWS::EC2::Instance'
    Properties:
      LaunchTemplate:
        LaunchTemplateName: !Ref MyLaunchTemplate
      SecurityGroupIds:
        - !Ref MySecurityGroup
  MyEC2Instance3:
    Type: 'AWS::EC2::Instance'
    Properties:
      LaunchTemplate:
        LaunchTemplateName: !Ref MyLaunchTemplate
      SecurityGroupIds:
        - !Ref MySecurityGroup
  MyEC2Instance4:
    Type: 'AWS::EC2::Instance'
    Properties:
      LaunchTemplate:
        LaunchTemplateName: !Ref MyLaunchTemplate
      SecurityGroupIds:
        - !Ref MySecurityGroup
  MyALB:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: 'my-alb'
      Scheme: 'internet-facing'
      Type: 'application'
      Subnets:
        - 'subnet-123456'
        - 'subnet-789012'
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
        - Key: 'Name'
          Value: 'my-alb'
  MyALBTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: 'my-alb-target-group'
      Port: 80
      Protocol: 'HTTP'
      TargetType: 'instance'
      VpcId: 'vpc-123