---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: 'MyLaunchTemplate'
      LaunchTemplateData:
        ImageId: 'ami-0557a15b87f6559cf'  # Ubuntu 20.04 LTS
        InstanceType: 't2.micro'
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            echo "<?php echo 'Hello, World!'; ?>" > /var/www/html/index.php
            service apache2 start
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'My Security Group'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: '0.0.0.0/0'
  MyDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: 'my-database-instance'
      DBInstanceClass: 'db.t2.micro'
      Engine: 'mysql'
      EngineVersion: '5.7.30'
      DBName: 'mydatabase'
      MasterUsername: 'myusername'
      MasterUserPassword: 'mypassword'
      VPCSecurityGroups:
        - !Ref MySecurityGroup
      DBSubnetGroupName: 'mydatabase-subnet-group'
      AllocatedStorage: '20'